### ISSUE TITLE
Empty codon tables return panic instead of error when optimizing

### ISSUE THREAD

**Issue by Koeng101** [TimothyStiles/poly#134]
**Describe the bug**
If you pass an empty codon table into optimize, you get the following error:
```
--- FAIL: TestFixCds (0.00s)
panic: invalid argument to Intn [recovered]
        panic: invalid argument to Intn

goroutine 14 [running]:
testing.tRunner.func1.2(0x728e00, 0x7c0620)
        /usr/lib/go/src/testing/testing.go:1143 +0x332
testing.tRunner.func1(0xc000297e00)
        /usr/lib/go/src/testing/testing.go:1146 +0x4b6
panic(0x728e00, 0x7c0620)
        /usr/lib/go/src/runtime/panic.go:965 +0x1b9
math/rand.(*Rand).Intn(0xc000104330, 0x0, 0xc0001007e0)
        /usr/lib/go/src/math/rand/rand.go:169 +0x9d
math/rand.Intn(...)
        /usr/lib/go/src/math/rand/rand.go:337
github.com/mroth/weightedrand.Chooser.Pick(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/koeng/go/pkg/mod/github.com/mroth/weightedrand@v0.2.1/weightedrand.go:48 +0x3b
github.com/TimothyStiles/poly.Optimize(0x787c82, 0x35b, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/koeng/go/src/github.com/TimothyStiles/poly/transformations.go:112 +0x299
github.com/TimothyStiles/poly.TestFixCds(0xc000297e00)
        /home/koeng/go/src/github.com/TimothyStiles/poly/synthesis_test.go:68 +0x385
testing.tRunner(0xc000297e00, 0x78a0e0)
        /usr/lib/go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
        /usr/lib/go/src/testing/testing.go:1238 +0x2b3
exit status 2
FAIL    github.com/TimothyStiles/poly   0.222s
```

Instead, you should get an error.

**Comment by TimothyStiles** [comment]
@Koeng101 can you add error handling to this? I'd be happy to merge.
