### ISSUE TITLE
Codon optimize does not check if amino acids are in table

### ISSUE THREAD

**Issue by Koeng101** [TimothyStiles/poly#201]
```
MGHHHHHHSKIFKOKNNYTOPKVFRDGCVPREIVYLPGNPAEIVLSTGERKIASCLHCPDAPCLSFKDHELQNSAFPEFPODQSAAVCATNAIAWDNENGIPVVDNNRCISCGICVDRCPVGAIYMIEEGIEINNNHIGDYLINLDEDDGDPSKIFGEKMYLLSEVKRSGKLKIETDEVITNIYNQLALIDLDAQFPNIFSRNLLMTLGTTCSIRRRGDVNVRMDAVLGPPGTNYGVMEVEFDSNALLDSPRNILDDLAVLSSRYGINYSDITPVIVSIAFPNTRSEYWRVINDINNVLQIKINSITIGALILLIWNLKKVNFNTDSFYADSECMEIRSSIANIIGDNPNISIGGILEVAK  }
panic: invalid argument to Intn

goroutine 22 [running]:
math/rand.(*Rand).Intn(0xc000656000, 0xc00006bb34)
        /usr/lib/go/src/math/rand/rand.go:168 +0x65
math/rand.Intn(...)
        /usr/lib/go/src/math/rand/rand.go:337
github.com/mroth/weightedrand.Chooser.Pick({{0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x0})
        /home/koeng/go/pkg/mod/github.com/mroth/weightedrand@v0.4.1/weightedrand.go:84 +0x4a
```

Basically, if you put in a protein sequence with invalid amino acids (in this case, O) optimize will panic instead of returning "hey you can't use that amino acid, idiot".

**Comment by fialhopm** [comment]
Hi @Koeng101, would it be ok if I gave this a shot?

**Comment by Koeng101** [comment]
> Hi @Koeng101, would it be ok if I gave this a shot?

That would be fantastic!
